#!/bin/bash


# Function to display messages
echo_message() {
    echo -e "\033[1;32m$1\033[0m"
}

echo_message "Do you want to install the wings? (yes/no)"
read answer

if [ "$answer" != "yes" ]; then
    echo_message "Installation aborted."
    exit 0
fi

echo_message "* Installing Dependencies"

# Update package list and install dependencies
apt update

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

# wings
mkdir -p wings
cd wings
git clone https://github.com/achul123/skyportd.git
cd wings
npm install

echo_message "* cd skyportd"

echo_message "* paste your configure code"

echo_message "* node ."

