#!/bin/bash


# Function to display messages
echo_message() {
    echo -e "\033[1;32m$1\033[0m"
}

echo_message "Do you want to install the wings? (yes/no)"
read answer

if [ "$answer" != "yes" ]; then
    echo_message "Installation aborted."
    exit 0
fi


git clone https://github.com/achul123/skyportd.git
cd skyportd 
npm install

echo_message "* cd /skyportd/skyportd"

echo_message "* paste your configure code"

echo_message "* pm2 start ."

